query PostIndexPage {
  posts {
    id
    title
  }
}

query PostShowPage($id: Int!) {
  post(id: $id) {
    id
    title
    userId
    content
    publishAt
    createdAt
    deletedAt
    updatedAt
  }
}
